"""empty message

Revision ID: 1ab214edfde6
Revises: 413049c3c46f
Create Date: 2015-11-08 01:01:46.846345

"""

# revision identifiers, used by Alembic.
revision = '1ab214edfde6'
down_revision = '413049c3c46f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interests')
    op.add_column('users', sa.Column('interests', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interests')
    op.create_table('interests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'interests_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'interests_pkey')
    )
    ### end Alembic commands ###
