"""empty message

Revision ID: 1bf3e6e7226e
Revises: 54011c917320
Create Date: 2015-11-07 17:51:54.184134

"""

# revision identifiers, used by Alembic.
revision = '1bf3e6e7226e'
down_revision = '54011c917320'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_identifier', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('user_identifier', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'user_identifier_id_fkey', 'user_identifier', type_='foreignkey')
    op.create_foreign_key(None, 'user_identifier', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_identifier', 'projects', ['project_id'], ['id'])
    op.drop_column('user_identifier', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_identifier', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_identifier', type_='foreignkey')
    op.drop_constraint(None, 'user_identifier', type_='foreignkey')
    op.create_foreign_key(u'user_identifier_id_fkey', 'user_identifier', 'projects', ['id'], ['id'])
    op.drop_column('user_identifier', 'user_id')
    op.drop_column('user_identifier', 'project_id')
    ### end Alembic commands ###
