"""empty message

Revision ID: 2e2545586029
Revises: None
Create Date: 2015-11-07 15:31:14.144237

"""

# revision identifiers, used by Alembic.
revision = '2e2545586029'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=40), nullable=True))
    op.drop_column('user', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    ### end Alembic commands ###
