"""empty message

Revision ID: 5313b2c16427
Revises: 53252271ae1
Create Date: 2015-11-07 20:27:54.228479

"""

# revision identifiers, used by Alembic.
revision = '5313b2c16427'
down_revision = '53252271ae1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'image',
               existing_type=sa.TEXT(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'image',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###
