"""empty message

Revision ID: f902acb0315
Revises: 537d2854c096
Create Date: 2015-11-08 02:08:13.156549

"""

# revision identifiers, used by Alembic.
revision = 'f902acb0315'
down_revision = '537d2854c096'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    ### end Alembic commands ###
